### 2. numpy random 

- seed: 랜덤값을 설정값 
- rand : 균등분포로 난수를 발생 ( 뽑힐 확률이 균등 )
- randn : 정규분포로 난수를 발생 ( 0 에서 가까운 데이터가 뽑힐 확률이 높음 `확률 불균등` `실생활 활용 높음` )
- ranint : 균등분포로 정수값을 발생 
- suffle : 행렬 데이터를 섞어 준다. 
- choice : 특정 확률로 데이터를 선택한다.


In [18]:
# seed 
# 일종 우리가 비밀번호를 암호화 하고 , 
# 비밀번호를 입력시 같은 형태로 암호화 되는 것과 같다. 

np.random.seed(1) 

result1 = np.random.randint (10, 100, 10)


np.random.seed(1) 

result2 = np.random.randint (10, 100, 10)

np.random.seed(3) 

result3 = np.random.randint (10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([34, 13, 66, 82, 10, 31, 29, 84, 51, 20]))

In [12]:
# rand 

np.random.rand(10)

array([0.55315267, 0.03319343, 0.13132283, 0.29698702, 0.36259969,
       0.1178732 , 0.92679611, 0.41885036, 0.90313508, 0.6202898 ])

In [11]:
# randn 

np.random.randn(10)

array([ 0.3130327 , -1.46599677, -1.84266059, -0.9540866 , -0.6312483 ,
       -0.77331752, -0.06460783, -1.70175816, -0.21198452,  2.07267323])

In [31]:
# suffle 

r = np.random.randint(1, 10, (3, 4))

r

array([[8, 1, 1, 2],
       [8, 9, 8, 5],
       [1, 1, 5, 4]])

In [34]:
np.random.shuffle(r)
r

array([[8, 9, 8, 5],
       [1, 1, 5, 4],
       [8, 1, 1, 2]])

In [38]:
# choice 
# 5까지 (0 ~ 4 까지) (python random 은 끝 숫자가 들어가지만 numpy는 끝숫자 빼고..)
# 두번째 인자는 10개 
# 세번째 퍼센티지 (합쳐서 숫자가 1이 되어야 한다) [확률 조작..]
np.random.choice(5, 10, p = [0.1, 0, 0.4, 0.2, 0.3])

array([3, 0, 2, 4, 4, 2, 2, 2, 2, 0])

In [43]:
#unique 유일한 값들을 뽑아준다. 
numbers, counts = np.unique(r, return_counts = True)

print(numbers)
print(counts)

[1 2 4 5 8 9]
[4 1 1 2 3 1]



### 행렬 데이터의 결합 
- concatenate 


In [8]:
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(3,2))
na3 = np.random.randint(10, size=(3,3))

In [9]:
# 세로 결합 
# 차원이 맞아야 결합이 된다.

na1



array([[0, 8, 1],
       [4, 5, 8]])

In [48]:
na2

array([[8, 4],
       [7, 8],
       [5, 6]])

In [49]:
na3

array([[7, 3, 5],
       [1, 8, 9],
       [2, 9, 8]])

In [52]:
#세로 결합
# axis default 0인데 이게 세로 설정 1이면 가로 설정(이건.. 라이브러리 마다 다름) 
np.concatenate((na1,na3))

array([[1, 3, 7],
       [4, 9, 0],
       [7, 3, 5],
       [1, 8, 9],
       [2, 9, 8]])

In [54]:
# 가로 결합 
np.concatenate((na2, na3), axis=1)

array([[8, 4, 7, 3, 5],
       [7, 8, 1, 8, 9],
       [5, 6, 2, 9, 8]])

In [59]:
# c_, r_ (이렇게 써서도 결합할 수 있다.)

# column 결합 
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
# row 결합 
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])